/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
	export interface GlobalComponents {
		VxeColumn: (typeof import('vxe-table/es/column/index.js'))['VxeColumn'];
		VxeTable: (typeof import('vxe-table/es/table/index.js'))['VxeTable'];
	}
}
